# docker-compose.yml
version: '3.8'

services:
  users-service:
    build:
      context: ./users
      additional_contexts:
        api-gateway-root: ../api-gateway
    ports:
      - '3000:3000'
    networks:
      - api-gateway

  products-service:
    build:
      context: ./products
      additional_contexts:
        api-gateway-root: ../api-gateway
    ports:
      - '3001:3001'
    networks:
      - api-gateway

  kong:
    image: kong:latest
    environment:
      - KONG_DATABASE=off
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_DECLARATIVE_CONFIG=/kong.yml
    ports:
      - '8000:8000'
      - '8001:8001'
    volumes:
      - ./kong.yml:/kong.yml
    networks:
      - api-gateway

networks:
  api-gateway:
