version: '3.8'

services:
  orchestrator:
    build:
      context: ./orchestrator
      additional_contexts:
        root: ../..
    container_name: orchestrator
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - RABBITMQ_PROTOCOL=amqp
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=default
      - RABBITMQ_PASSWORD=default
      - RABBITMQ_VHOST=/
    depends_on:
      rabbitmq:
        condition: 'service_started'
    networks:
      - saga-network

  inventory:
    build:
      context: ./inventory
      additional_contexts:
        root: ../..
    container_name: inventory
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - RABBITMQ_PROTOCOL=amqp
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=default
      - RABBITMQ_PASSWORD=default
      - RABBITMQ_VHOST=/
    depends_on:
      rabbitmq:
        condition: 'service_started'
    networks:
      - saga-network

  orders:
    build:
      context: ./orders
      additional_contexts:
        root: ../..
    container_name: orders
    ports:
      - '3002:3002'
    environment:
      - PORT=3002
      - RABBITMQ_PROTOCOL=amqp
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=default
      - RABBITMQ_PASSWORD=default
      - RABBITMQ_VHOST=/
    depends_on:
      rabbitmq:
        condition: 'service_started'
    networks:
      - saga-network

  notifier:
    build:
      context: ./notifier
      additional_contexts:
        root: ../..
    container_name: notifier
    ports:
      - '3003:3003'
    environment:
      - PORT=3003
    networks:
      - saga-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: saga-orchestration
    environment:
      - RABBITMQ_DEFAULT_USER=default
      - RABBITMQ_DEFAULT_PASS=default
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - saga-network

networks:
  saga-network:
