services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: eda
    environment:
      - RABBITMQ_DEFAULT_USER=default
      - RABBITMQ_DEFAULT_PASS=default
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - event-driven-network

  stock-price-service:
    build:
      context: ./stock-price
      additional_contexts:
        root: ../event-driven-architecture
    container_name: stock-price
    environment:
      - PORT=3000
      - RABBITMQ_PROTOCOL=amqp
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=default
      - RABBITMQ_PASSWORD=default
      - RABBITMQ_VHOST=/
    depends_on:
      rabbitmq:
        condition: 'service_started'
    ports:
      - 3000:3000
    networks:
      - event-driven-network

  market-news-service:
    build:
      context: ./market-news
      additional_contexts:
        root: ../event-driven-architecture
    container_name: market-news
    environment:
      - PORT=3001
      - RABBITMQ_PROTOCOL=amqp
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=default
      - RABBITMQ_PASSWORD=default
      - RABBITMQ_VHOST=/
    depends_on:
      rabbitmq:
        condition: 'service_started'
    ports:
      - 3001:3001
    networks:
      - event-driven-network

  portfolio-manager-service:
    build:
      context: ./portfolio-manager
      additional_contexts:
        root: ../event-driven-architecture
    container_name: portfolio-manager
    environment:
      - RABBITMQ_PROTOCOL=amqp
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=default
      - RABBITMQ_PASSWORD=default
      - RABBITMQ_VHOST=/
    depends_on:
      rabbitmq:
        condition: 'service_started'
    command:
      [
        './wait-for-it.sh',
        'rabbitmq:5672',
        '--',
        './wait-for-it.sh',
        'rabbitmq:15672',
        '--',
        'npm',
        'start',
      ]
    networks:
      - event-driven-network

  alert-service:
    build:
      context: ./alert
      additional_contexts:
        root: ../event-driven-architecture
    container_name: alert
    environment:
      - RABBITMQ_PROTOCOL=amqp
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=default
      - RABBITMQ_PASSWORD=default
      - RABBITMQ_VHOST=/
    depends_on:
      rabbitmq:
        condition: 'service_started'
    command:
      [
        './wait-for-it.sh',
        'rabbitmq:5672',
        '--',
        './wait-for-it.sh',
        'rabbitmq:15672',
        '--',
        'npm',
        'start',
      ]
    networks:
      - event-driven-network

  dashboard-service:
    build:
      context: ./dashboard
      additional_contexts:
        root: ../event-driven-architecture
    container_name: dashboard
    environment:
      - RABBITMQ_PROTOCOL=amqp
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=default
      - RABBITMQ_PASSWORD=default
      - RABBITMQ_VHOST=/
    depends_on:
      rabbitmq:
        condition: 'service_started'
    command:
      [
        './wait-for-it.sh',
        'rabbitmq:5672',
        '--',
        './wait-for-it.sh',
        'rabbitmq:15672',
        '--',
        'npm',
        'start',
      ]
    networks:
      - event-driven-network

networks:
  event-driven-network:
